#deploymens vem de aps/v1
apiVersion: apps/v1
#tipo
kind: Deployment
metadata:
  #nome do deployment
  name: mss-user-deployment
spec:
  #quantas cópias
  replicas: 1
  #para especificar o rótulo
  selector:
    matchLabels:
      #rótulo, app não tem nada de especial, pode ser qq coisa
      #Deployment vai selecionar todo Pod que tiver esse rótulo
      app: mss-user
  #modelo que vai ser usado para construção dos Pods
  template:
    metadata:
      labels:
        #os Pods terão esse rótulo, assim,
        #serão selecionados por esse deployment
        app: mss-user
    spec:
      containers:
        - name: mss-user
          image: arcatron/mss-user
          resources:
            limits:
              memory: 256Mi
              cpu: 1
---
apiVersion: v1
kind: Service
metadata:
  name: mss-user-clusterip-service
spec:
  #ip interno ao cluster
  type: ClusterIP
  selector:
    app: mss-user
  ports:
    - name: mss-user
      protocol: TCP
      port: 4000
      targetPort: 4000
