name: Testes unitários automatizados

on: [push]

jobs:
  testes:
    name: Testes TDD
    runs-on: ubunto-latest

    steps:
      - name: Get Code
        uses: actions/checkout@v2

      - name: Config Node
        uses: actions/setup-node@v3

      - name: Install Dependencies
        run: npm install

      - name: Run tests
        run: npx jest ./mss-product/tests/repositories/orderRepositoryTest.test.js
